### ISSUE TITLE
`main` panics at `font.rs:23:67`

### ISSUE THREAD

**Issue by MrVeink** [oknozor/onagre#43]
When running `~/.cargo/bin/onagre -t /home/veikko/.config/onagre/theme.toml` I get the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotFound', src/style/font.rs:23:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I am using the `simple-theme.toml` and Alpine 3.15 with Sway as the WM.

Running bash -c `"RUST_BACKTRACE=1 cargo run --bin onagre"` outputs:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s
     Running `target/debug/onagre`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotFound', src/style/font.rs:23:67
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
             at /home/buildozer/aports/community/rust/src/rustc-1.57.0-src/library/core/src/result.rs:1298:23
   4: onagre::style::font::load
             at ./src/style/font.rs:23:18
   5: onagre::app::run::{{closure}}
             at ./src/app/mod.rs:39:21
   6: core::option::Option<T>::map
             at /home/buildozer/aports/community/rust/src/rustc-1.57.0-src/library/core/src/option.rs:848:29
   7: onagre::app::run
             at ./src/app/mod.rs:36:24
   8: onagre::main
             at ./src/bin/onagre.rs:56:5
   9: core::ops::function::FnOnce::call_once
             at /home/buildozer/aports/community/rust/src/rustc-1.57.0-src/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MrVeink** [comment]
Fixed.
The font was missing. Sorry for the inconvinience. I am very tired. Cause I use Alpine I just `doas apk add font-iosevka`
